spring:
  jpa:
    generate-ddl: true
    proerties:
      hibernate:
        ddl-auto: generate
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect:
    url: jdbc:mysql://localhost:3306/temp_user_module
    username: root
    password: root